### ISSUE TITLE
Incompatibility with TerraBlender

### ISSUE THREAD

**Issue by MuteTiefling** [AlexModGuy/Citadel#101]
Details here: https://github.com/Glitchfiend/TerraBlender/issues/107

When Citadel is installed, extra values are being injected into level.data that then get copied/cloned/re-written incorrectly with each save. Eventually the world fails to load because there are too many nested NBT values. 

Removing Citadel and making a new world resolves the issue.

**Comment by aAndrew3030** [comment]
https://github.com/AlexModGuy/AlexsMobs/issues/1475
