### ISSUE TITLE
mod is rickrolling on april 1st

### ISSUE THREAD

**Issue by Seegras** [AlexModGuy/Citadel#109]
It downloads 20MB rickroll.mp4 from archive.org and plays this on the main menu. 

It might interfere with fancymenu, because the whole menu is invisible; making the starting of a game or changing options rather difficult. I consider this a bug. 

Also, it appears to wreak havoc on servers.

**Comment by Gbergz** [comment]
can confirm, an "april fools" config entry would be handy.

**Comment by MapperTV** [comment]
This is a VERY bad thing.

Not only you force-download a 21MB video file without any warning or user consent, you also play a COPYRIGHTED music in the menu. This will cause trouble to anyone who decided to stream today.

I'm not even talking about potential security risks into downloading and playing stuff directly without apparent safety measures.

And all of this without any possible configuration?

Thank you far making us hating this stupid day even more.

**Comment by AlexModGuy** [comment]
adding a config right now for this. sorry for the trouble caused, truly.
