### ISSUE TITLE
just wanna say...

### ISSUE THREAD

**Issue by movte** [AlexModGuy/Citadel#114]
your clowns, take a rope ty

**Comment by TheWitherlord** [comment]
Don’t ever tell somebody to do that you low life.

Over a harmless joke on April fools?

**Comment by Xplodin** [comment]
> your clowns, take a rope ty

wtf dude.
The reddit post I made was never meant to get this much attention yet here we are.
AlexModGuy I am so sorry you are getting this much shit from it.
