### ISSUE TITLE
Rick Roll video blocks startup menu

### ISSUE THREAD

**Issue by Kdschar** [AlexModGuy/Citadel#116]
I'm using the Cottage Witch modpack from CurseForge and there are no buttons on the screen when the launcher plays the Rick Roll video. I literally can't play my game because the video is taking over everything.

Even with deleting the file in citadel\video_cache and adding an empty rickroll.mp4 to "fool" the mod, it downloads a new copy and screws my game over anyway.

**Comment by Sebas-Re** [comment]
funny mod haha...

**Comment by AlexModGuy** [comment]
replaced with a tetris-esque falling block game for next year 👍
