### ISSUE TITLE
near instantly crashes the game

### ISSUE THREAD

**Issue by yoopgim** [AlexModGuy/Citadel#135]
on 1.20.1, overwolf curseforge, forge 47.2.0. the game opens, loads untill "scanning mod candidates" then crashes with error code 1 and no log. i have nothing else enabled but citadel

**Comment by Gwen-digo** [comment]
having the same issue but got a log, posted it in the alex's caves area too but here it is 

[alexcavecrash.txt](https://github.com/AlexModGuy/Citadel/files/13061481/alexcavecrash.txt)

**Comment by Gwen-digo** [comment]
i got mine figured out, i had to update my amd drivers

**Comment by yoopgim** [comment]
what are amd drivers?
