### ISSUE TITLE
my server crashed

### ISSUE THREAD

**Issue by jojofenin99** [AlexModGuy/Citadel#138]
here is the crash log:
[crash-2023-10-22_11.34.30-server.txt](https://github.com/AlexModGuy/Citadel/files/13083418/crash-2023-10-22_11.34.30-server.txt)

**Comment by AlexModGuy** [comment]
not my mod
> 	at net.mehvahdjukaar.supplementaries.common.block.tiles.DoormatBlockTile.m_142466_(DoormatBlockTile.java:43) ~[supplementaries-1.20-2.6.15.jar%23681!/:?] {re:classloading}
