### ISSUE TITLE
[1.20.1] java.lang.IllegalStateException: Field f_47443_ is not private and an instance field

### ISSUE THREAD

**Issue by Vivid141** [AlexModGuy/Citadel#153]
https://mclo.gs/SnwHR8W
**Minecraft Version:** 1.20.1
**Forge Version:** 47.2.20
**Citadel Version:** 2.5.3

**Comment by AlexModGuy** [comment]
> 	at com.ordana.immersive_weathering.blocks.LeafPileBlock.m_213898_(LeafPileBlock.java:249) ~[immersive_weathering-1.20.1-2.0.0-forge.jar%23365!/:?] {re:classloading}

crash with immersive weathering mod not citadel
