### ISSUE TITLE
Citadel Incompatibility with Distant Horizons latest version 2.1.0a

### ISSUE THREAD

**Issue by darkdark130** [AlexModGuy/Citadel#176]
latest version of Distant Horizons 2.1.0a does not work at all with Citadel

**Comment by Mikecerc** [comment]
Can confirm I am experiencing the same issue with 2.1.0a on version 1.20.1

**Comment by Azaysol** [comment]
If you're playing Alex's Caves in latest version, try configure "biome_ambient_light_coloring = false" in alexscaves_client file
