### ISSUE TITLE
Server boot indefinitely class error

### ISSUE THREAD

**Issue by Ju4mpizel** [AlexModGuy/Citadel#180]
Mi servidor tiene estos errores desde ayer por alguna razon este se queda en un booteo infinito por culpa de un error de las clases de citadel no tengo manera de solucionarlo si alguien me puede ayudar
My server has had these errors since yesterday for some reason it stays in an infinite boot due to an error in the citadel classes I have no way to solve it if someone can help me

Here are the logs of the errors:
https://paste.sparked.host/nevazapowu.apache

**Comment by Bohemiangrove666** [comment]
I'm having the same trouble.
Any solution?

Estoy teniendo el mismo problema
Encontraste solucion?

**Comment by santiagortizgue** [comment]
Same for me! Hosted on Sparked Host,

**Comment by Ju4mpizel** [comment]
There is no solution for now, no one responds, neither does the creator, there has been this class error for a long time and it is the citadel because it is the one that causes this infinite start

**Comment by Ju4mpizel** [comment]
Apparently it is caused by the Alex caves mod

**Comment by Bohemiangrove666** [comment]
Hello.

For everyone wondering, it's SparkedHost problem. They already solved it (apparently)
