### ISSUE TITLE
1.19 forge crashes before it can even start

### ISSUE THREAD

**Issue by Thisguyneedshelp** [AlexModGuy/Citadel#82]
the latest update causes my modpack to crash without any real reason given, and even after changing citadel back to previous versions or removing it entirely the problem persists, please help, heres the logs https://mclo.gs/G0lhzAo

**Comment by NielsPilgaard** [comment]
Downgrading to `citadel-1.12.7-1.19` fixes the issue :)

**Comment by desbarmitar** [comment]
Dont duplicate issues, is harder for the devs to review. Reply to the ones already created.
Previous issue: https://github.com/AlexModGuy/Citadel/issues/81

**Comment by AlexModGuy** [comment]
fixed in 1.12.11.
