### ISSUE TITLE
Citadel Breaks compability of Rubidium 1.19.2

### ISSUE THREAD

**Issue by Zelioth** [AlexModGuy/Citadel#87]
Recently after a lot of testing I found that Citadel breaks Rubidium and it's addon mods. This issue seems to only be present when Citadel is active in the mods folder and when turned off the client launches just fine.

This can be recreated by simple putting Citadel and Rubidium Forge versions into a Forge instance of 1.19.2 and pressing play

Minecraft 1.19.2
Forge. All Versions
Citadel 1.12.12 to 1.13.1

**Comment by kjstahl** [comment]
I am also having this issue. 1.13.0 worked fine with Rubidium and also Rubidium Extras, thought Extras was working fine using the  [trick posted here.](https://github.com/dimadencep/sodium-extra-forge/issues/21#issuecomment-1238928958).

With the newest update, 1.13.1, the launcher instantly crashes upon pressing play.

**Comment by KowalskiXCIX** [comment]
Same Issue Here, Any version above 1.13.0 with rubidium causes major issues

**Comment by AlexModGuy** [comment]
fixed in 2.0.0

**Comment by Zelioth** [comment]
I'm confused, wasn't this issue fixed in 1.13.3 when we went through it on discord and I tested the version for you?

**Comment by AlexModGuy** [comment]
there was an addittional mixin call I removed that has also been causing some trouble

**Comment by Zelioth** [comment]
Oh okay I apologize, Wanted to make sure I wasn't missing something. I appreciate your hard work
