### ISSUE TITLE
Causes Holograms from HolographicDisplays plugin to disappear

### ISSUE THREAD

**Issue by FloofyCandy** [AlexModGuy/Citadel#95]
I have no clue how this mod even relates to the holograms from HolographicDisplays but somehow it is messing with them. When a player leaves the chunk either by moving away or teleporting to a different world, then goes back to where the hologram is, it is gone. When I run /hd reload then the hologram reappears. Hopefully this is fixable but if not, thank you for your time.

Citadel Version: 2.1.0-1.19
Java Version: 17.0.2
Forge Version: 1.19.2-43.1.52

The server is running Arclight 1.19.2, that is how I am able to have mods and plugins.

**Comment by DarthChungo** [comment]
Still experiencing this issue running a paper server as a lobby, with forge clients passing through it to access another forge server. I'm running citadel version 1.11.3-1.18.2. Do you have any workarounds?
